[env]
WINIT_X11_SCALE_FACTOR = "1.2"
[font]
size = 9.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"
[window]
opacity = 0.92
